param(
    [string]$InputCsv = ".\princess_parts_products.csv",
    [string]$OutputSql = ".\princess_parts_analytics_sqlite.sql",
    [string]$SourceSite = "https://parts.princess.co.uk/",
    [string]$SourceFileLabel
)

$ErrorActionPreference = 'Stop'

function Convert-ToSqlTextLiteral {
    param([AllowNull()][string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return 'NULL'
    }

    $escaped = $Value.Replace("'", "''")
    return "'$escaped'"
}

function Convert-ToSqlNumericLiteral {
    param([AllowNull()][string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return 'NULL'
    }

    return $Value.Trim()
}

if (-not (Test-Path -LiteralPath $InputCsv)) {
    throw "Fichier CSV introuvable: $InputCsv"
}

$rows = Import-Csv -LiteralPath $InputCsv
if (-not $rows -or $rows.Count -eq 0) {
    throw "Le fichier CSV ne contient aucune ligne exploitable: $InputCsv"
}

$snapshotDate = if ($rows[0].date) { $rows[0].date } else { (Get-Date).ToString('yyyy-MM-dd') }
$generatedAt = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
$sourceFile = if ([string]::IsNullOrWhiteSpace($SourceFileLabel)) { Split-Path -Leaf $InputCsv } else { $SourceFileLabel }
$runKey = "$snapshotDate|$sourceFile"

$builder = New-Object System.Text.StringBuilder

[void]$builder.AppendLine('-- Princess Parts analytics schema for SQLite')
[void]$builder.AppendLine("-- Generated on $generatedAt")
[void]$builder.AppendLine("-- Snapshot date $snapshotDate")
[void]$builder.AppendLine('')
[void]$builder.AppendLine('PRAGMA foreign_keys = ON;')
[void]$builder.AppendLine('BEGIN TRANSACTION;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('CREATE TABLE IF NOT EXISTS import_runs (')
[void]$builder.AppendLine('    import_run_id INTEGER PRIMARY KEY AUTOINCREMENT,')
[void]$builder.AppendLine('    run_key TEXT NOT NULL UNIQUE,')
[void]$builder.AppendLine('    snapshot_date TEXT NOT NULL,')
[void]$builder.AppendLine('    run_timestamp TEXT NOT NULL,')
[void]$builder.AppendLine('    source_site TEXT NOT NULL,')
[void]$builder.AppendLine('    source_file TEXT,')
[void]$builder.AppendLine('    row_count INTEGER NOT NULL,')
[void]$builder.AppendLine('    status TEXT NOT NULL DEFAULT ''loaded'',')
[void]$builder.AppendLine('    notes TEXT')
[void]$builder.AppendLine(');')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('CREATE TABLE IF NOT EXISTS princess_parts_history (')
[void]$builder.AppendLine('    snapshot_date TEXT NOT NULL,')
[void]$builder.AppendLine('    import_run_id INTEGER,')
[void]$builder.AppendLine('    category TEXT,')
[void]$builder.AppendLine('    category_fr TEXT,')
[void]$builder.AppendLine('    name TEXT,')
[void]$builder.AppendLine('    name_fr TEXT,')
[void]$builder.AppendLine('    description TEXT,')
[void]$builder.AppendLine('    description_fr TEXT,')
[void]$builder.AppendLine('    specifications TEXT,')
[void]$builder.AppendLine('    specifications_fr TEXT,')
[void]$builder.AppendLine('    model_number TEXT,')
[void]$builder.AppendLine('    price_gbp_numeric REAL,')
[void]$builder.AppendLine('    price_euro_numeric REAL,')
[void]$builder.AppendLine('    price_dollar_numeric REAL,')
[void]$builder.AppendLine('    stock INTEGER,')
[void]$builder.AppendLine('    delivery_delay TEXT,')
[void]$builder.AppendLine('    delivery_delay_fr TEXT,')
[void]$builder.AppendLine('    url TEXT NOT NULL,')
[void]$builder.AppendLine('    loaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,')
[void]$builder.AppendLine('    PRIMARY KEY (snapshot_date, url),')
[void]$builder.AppendLine('    FOREIGN KEY (import_run_id) REFERENCES import_runs(import_run_id)')
[void]$builder.AppendLine(');')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('CREATE INDEX IF NOT EXISTS idx_import_runs_snapshot_date ON import_runs (snapshot_date);')
[void]$builder.AppendLine('CREATE INDEX IF NOT EXISTS idx_princess_parts_history_url ON princess_parts_history (url);')
[void]$builder.AppendLine('CREATE INDEX IF NOT EXISTS idx_princess_parts_history_url_snapshot_date ON princess_parts_history (url, snapshot_date);')
[void]$builder.AppendLine('CREATE INDEX IF NOT EXISTS idx_princess_parts_history_model_number ON princess_parts_history (model_number);')
[void]$builder.AppendLine('CREATE INDEX IF NOT EXISTS idx_princess_parts_history_category ON princess_parts_history (category);')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('INSERT INTO import_runs (run_key, snapshot_date, run_timestamp, source_site, source_file, row_count, status, notes)')
[void]$builder.AppendLine("VALUES ($(Convert-ToSqlTextLiteral $runKey), $(Convert-ToSqlTextLiteral $snapshotDate), $(Convert-ToSqlTextLiteral $generatedAt), $(Convert-ToSqlTextLiteral $SourceSite), $(Convert-ToSqlTextLiteral $sourceFile), $($rows.Count), 'loaded', 'Initial load from generated CSV')")
[void]$builder.AppendLine('ON CONFLICT(run_key) DO UPDATE SET')
[void]$builder.AppendLine('    run_timestamp = excluded.run_timestamp,')
[void]$builder.AppendLine('    row_count = excluded.row_count,')
[void]$builder.AppendLine('    status = excluded.status,')
[void]$builder.AppendLine('    notes = excluded.notes;')
[void]$builder.AppendLine('')

foreach ($row in $rows) {
    [void]$builder.AppendLine('INSERT INTO princess_parts_history (')
    [void]$builder.AppendLine('    snapshot_date, import_run_id, category, category_fr, name, name_fr, description, description_fr,')
    [void]$builder.AppendLine('    specifications, specifications_fr, model_number, price_gbp_numeric, price_euro_numeric, price_dollar_numeric,')
    [void]$builder.AppendLine('    stock, delivery_delay, delivery_delay_fr, url')
    [void]$builder.AppendLine(') VALUES (')
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.date),")
    [void]$builder.AppendLine("    (SELECT import_run_id FROM import_runs WHERE run_key = $(Convert-ToSqlTextLiteral $runKey)),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.category),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.'Category (FR)'),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.name),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.'Name (FR)'),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.description),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.'Description (FR)'),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.specifications),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.'Specifications (FR)'),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.model_number),")
    [void]$builder.AppendLine("    $(Convert-ToSqlNumericLiteral $row.price_gbp_numeric),")
    [void]$builder.AppendLine("    $(Convert-ToSqlNumericLiteral $row.price_euro_numeric),")
    [void]$builder.AppendLine("    $(Convert-ToSqlNumericLiteral $row.price_dollar_numeric),")
    [void]$builder.AppendLine("    $(Convert-ToSqlNumericLiteral $row.stock),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.delivery_delay),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.'Delivery delay (FR)'),")
    [void]$builder.AppendLine("    $(Convert-ToSqlTextLiteral $row.url)")
    [void]$builder.AppendLine(')')
    [void]$builder.AppendLine('ON CONFLICT(snapshot_date, url) DO UPDATE SET')
    [void]$builder.AppendLine('    import_run_id = excluded.import_run_id,')
    [void]$builder.AppendLine('    category = excluded.category,')
    [void]$builder.AppendLine('    category_fr = excluded.category_fr,')
    [void]$builder.AppendLine('    name = excluded.name,')
    [void]$builder.AppendLine('    name_fr = excluded.name_fr,')
    [void]$builder.AppendLine('    description = excluded.description,')
    [void]$builder.AppendLine('    description_fr = excluded.description_fr,')
    [void]$builder.AppendLine('    specifications = excluded.specifications,')
    [void]$builder.AppendLine('    specifications_fr = excluded.specifications_fr,')
    [void]$builder.AppendLine('    model_number = excluded.model_number,')
    [void]$builder.AppendLine('    price_gbp_numeric = excluded.price_gbp_numeric,')
    [void]$builder.AppendLine('    price_euro_numeric = excluded.price_euro_numeric,')
    [void]$builder.AppendLine('    price_dollar_numeric = excluded.price_dollar_numeric,')
    [void]$builder.AppendLine('    stock = excluded.stock,')
    [void]$builder.AppendLine('    delivery_delay = excluded.delivery_delay,')
    [void]$builder.AppendLine('    delivery_delay_fr = excluded.delivery_delay_fr,')
    [void]$builder.AppendLine('    loaded_at = CURRENT_TIMESTAMP;')
    [void]$builder.AppendLine('')
}

[void]$builder.AppendLine('DROP VIEW IF EXISTS current_products;')
[void]$builder.AppendLine('CREATE VIEW current_products AS')
[void]$builder.AppendLine('WITH ranked AS (')
[void]$builder.AppendLine('    SELECT')
[void]$builder.AppendLine('        h.* ,')
[void]$builder.AppendLine('        ROW_NUMBER() OVER (PARTITION BY h.url ORDER BY h.snapshot_date DESC, h.import_run_id DESC, h.loaded_at DESC) AS row_num,')
[void]$builder.AppendLine('        MIN(h.snapshot_date) OVER (PARTITION BY h.url) AS first_seen_date,')
[void]$builder.AppendLine('        MAX(h.snapshot_date) OVER (PARTITION BY h.url) AS last_seen_date')
[void]$builder.AppendLine('    FROM princess_parts_history h')
[void]$builder.AppendLine(')')
[void]$builder.AppendLine('SELECT')
[void]$builder.AppendLine('    snapshot_date,')
[void]$builder.AppendLine('    import_run_id,')
[void]$builder.AppendLine('    category,')
[void]$builder.AppendLine('    category_fr,')
[void]$builder.AppendLine('    name,')
[void]$builder.AppendLine('    name_fr,')
[void]$builder.AppendLine('    description,')
[void]$builder.AppendLine('    description_fr,')
[void]$builder.AppendLine('    specifications,')
[void]$builder.AppendLine('    specifications_fr,')
[void]$builder.AppendLine('    model_number,')
[void]$builder.AppendLine('    price_gbp_numeric,')
[void]$builder.AppendLine('    price_euro_numeric,')
[void]$builder.AppendLine('    price_dollar_numeric,')
[void]$builder.AppendLine('    stock,')
[void]$builder.AppendLine('    CASE WHEN COALESCE(stock, 0) > 0 THEN 1 ELSE 0 END AS is_in_stock,')
[void]$builder.AppendLine('    delivery_delay,')
[void]$builder.AppendLine('    delivery_delay_fr,')
[void]$builder.AppendLine('    url,')
[void]$builder.AppendLine('    first_seen_date,')
[void]$builder.AppendLine('    last_seen_date')
[void]$builder.AppendLine('FROM ranked')
[void]$builder.AppendLine('WHERE row_num = 1;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('DROP VIEW IF EXISTS product_changes;')
[void]$builder.AppendLine('CREATE VIEW product_changes AS')
[void]$builder.AppendLine('WITH versioned AS (')
[void]$builder.AppendLine('    SELECT')
[void]$builder.AppendLine('        h.* ,')
[void]$builder.AppendLine('        LAG(h.snapshot_date) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_snapshot_date,')
[void]$builder.AppendLine('        LAG(h.name) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_name,')
[void]$builder.AppendLine('        LAG(h.category) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_category,')
[void]$builder.AppendLine('        LAG(h.description) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_description,')
[void]$builder.AppendLine('        LAG(h.delivery_delay) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_delivery_delay,')
[void]$builder.AppendLine('        LAG(h.stock) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_stock,')
[void]$builder.AppendLine('        LAG(h.price_gbp_numeric) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_price_gbp_numeric,')
[void]$builder.AppendLine('        LAG(h.price_euro_numeric) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_price_euro_numeric,')
[void]$builder.AppendLine('        LAG(h.price_dollar_numeric) OVER (PARTITION BY h.url ORDER BY h.snapshot_date, h.import_run_id, h.loaded_at) AS previous_price_dollar_numeric')
[void]$builder.AppendLine('    FROM princess_parts_history h')
[void]$builder.AppendLine(')')
[void]$builder.AppendLine('SELECT')
[void]$builder.AppendLine('    snapshot_date,')
[void]$builder.AppendLine('    previous_snapshot_date,')
[void]$builder.AppendLine('    url,')
[void]$builder.AppendLine('    model_number,')
[void]$builder.AppendLine('    category,')
[void]$builder.AppendLine('    previous_category,')
[void]$builder.AppendLine('    name,')
[void]$builder.AppendLine('    previous_name,')
[void]$builder.AppendLine('    price_gbp_numeric,')
[void]$builder.AppendLine('    previous_price_gbp_numeric,')
[void]$builder.AppendLine('    ROUND(price_gbp_numeric - previous_price_gbp_numeric, 2) AS price_delta_gbp,')
[void]$builder.AppendLine('    CASE')
[void]$builder.AppendLine('        WHEN previous_price_gbp_numeric IS NULL OR previous_price_gbp_numeric = 0 THEN NULL')
[void]$builder.AppendLine('        ELSE ROUND(((price_gbp_numeric - previous_price_gbp_numeric) / previous_price_gbp_numeric) * 100.0, 2)')
[void]$builder.AppendLine('    END AS price_delta_pct,')
[void]$builder.AppendLine('    stock,')
[void]$builder.AppendLine('    previous_stock,')
[void]$builder.AppendLine('    stock - previous_stock AS stock_delta,')
[void]$builder.AppendLine('    delivery_delay,')
[void]$builder.AppendLine('    previous_delivery_delay,')
[void]$builder.AppendLine('    CASE WHEN previous_snapshot_date IS NULL THEN 1 ELSE 0 END AS is_new_product,')
[void]$builder.AppendLine('    CASE WHEN previous_price_gbp_numeric IS NOT NULL AND IFNULL(price_gbp_numeric, -1) <> IFNULL(previous_price_gbp_numeric, -1) THEN 1 ELSE 0 END AS price_changed,')
[void]$builder.AppendLine('    CASE WHEN previous_stock IS NOT NULL AND IFNULL(stock, -999999) <> IFNULL(previous_stock, -999999) THEN 1 ELSE 0 END AS stock_changed,')
[void]$builder.AppendLine('    CASE WHEN previous_delivery_delay IS NOT NULL AND IFNULL(delivery_delay, '''') <> IFNULL(previous_delivery_delay, '''') THEN 1 ELSE 0 END AS delivery_delay_changed,')
[void]$builder.AppendLine('    CASE WHEN previous_name IS NOT NULL AND IFNULL(name, '''') <> IFNULL(previous_name, '''') THEN 1 ELSE 0 END AS name_changed,')
[void]$builder.AppendLine('    CASE WHEN previous_category IS NOT NULL AND IFNULL(category, '''') <> IFNULL(previous_category, '''') THEN 1 ELSE 0 END AS category_changed,')
[void]$builder.AppendLine('    CASE WHEN previous_description IS NOT NULL AND IFNULL(description, '''') <> IFNULL(previous_description, '''') THEN 1 ELSE 0 END AS description_changed')
[void]$builder.AppendLine('FROM versioned;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('DROP VIEW IF EXISTS price_history;')
[void]$builder.AppendLine('CREATE VIEW price_history AS')
[void]$builder.AppendLine('SELECT')
[void]$builder.AppendLine('    snapshot_date,')
[void]$builder.AppendLine('    url,')
[void]$builder.AppendLine('    model_number,')
[void]$builder.AppendLine('    name,')
[void]$builder.AppendLine('    category,')
[void]$builder.AppendLine('    price_gbp_numeric,')
[void]$builder.AppendLine('    previous_price_gbp_numeric,')
[void]$builder.AppendLine('    price_delta_gbp,')
[void]$builder.AppendLine('    price_delta_pct')
[void]$builder.AppendLine('FROM product_changes;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('DROP VIEW IF EXISTS stock_history;')
[void]$builder.AppendLine('CREATE VIEW stock_history AS')
[void]$builder.AppendLine('SELECT')
[void]$builder.AppendLine('    snapshot_date,')
[void]$builder.AppendLine('    url,')
[void]$builder.AppendLine('    model_number,')
[void]$builder.AppendLine('    name,')
[void]$builder.AppendLine('    category,')
[void]$builder.AppendLine('    stock,')
[void]$builder.AppendLine('    previous_stock,')
[void]$builder.AppendLine('    stock_delta,')
[void]$builder.AppendLine('    CASE WHEN COALESCE(stock, 0) > 0 THEN 1 ELSE 0 END AS is_in_stock,')
[void]$builder.AppendLine('    CASE WHEN COALESCE(previous_stock, 0) > 0 THEN 1 ELSE 0 END AS was_in_stock,')
[void]$builder.AppendLine('    CASE WHEN COALESCE(previous_stock, 0) > 0 AND COALESCE(stock, 0) = 0 THEN 1 ELSE 0 END AS became_out_of_stock,')
[void]$builder.AppendLine('    CASE WHEN COALESCE(previous_stock, 0) = 0 AND COALESCE(stock, 0) > 0 THEN 1 ELSE 0 END AS back_in_stock')
[void]$builder.AppendLine('FROM product_changes;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('DROP VIEW IF EXISTS catalog_kpis_by_day;')
[void]$builder.AppendLine('CREATE VIEW catalog_kpis_by_day AS')
[void]$builder.AppendLine('SELECT')
[void]$builder.AppendLine('    snapshot_date,')
[void]$builder.AppendLine('    COUNT(*) AS product_count,')
[void]$builder.AppendLine('    SUM(CASE WHEN COALESCE(stock, 0) > 0 THEN 1 ELSE 0 END) AS in_stock_count,')
[void]$builder.AppendLine('    SUM(CASE WHEN COALESCE(stock, 0) = 0 THEN 1 ELSE 0 END) AS out_of_stock_count,')
[void]$builder.AppendLine('    ROUND(AVG(price_gbp_numeric), 2) AS avg_price_gbp,')
[void]$builder.AppendLine('    ROUND(MIN(price_gbp_numeric), 2) AS min_price_gbp,')
[void]$builder.AppendLine('    ROUND(MAX(price_gbp_numeric), 2) AS max_price_gbp')
[void]$builder.AppendLine('FROM princess_parts_history')
[void]$builder.AppendLine('GROUP BY snapshot_date')
[void]$builder.AppendLine('ORDER BY snapshot_date;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('COMMIT;')

$outputDirectory = Split-Path -Parent $OutputSql
if (-not [string]::IsNullOrWhiteSpace($outputDirectory) -and -not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

[System.IO.File]::WriteAllText($OutputSql, $builder.ToString(), [System.Text.Encoding]::UTF8)

Write-Host "SQL SQLite analytique ecrit dans $OutputSql"
Write-Host "Lignes chargees: $($rows.Count)"
Write-Host "Snapshot date: $snapshotDate"